# Generated by Django 4.2.7 on 2026-03-06 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='નામ')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='ઇમેઇલ')),
                ('age', models.IntegerField(verbose_name='ઉંમર')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='સર્જન સમય')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='અપડેટ સમય')),
            ],
            options={
                'verbose_name': 'વિદ્યાર્થી',
                'verbose_name_plural': 'વિદ્યાર્થીઓ',
                'ordering': ['-created_at'],
            },
        ),
    ]
